# Generated by Django 2.2.4 on 2020-03-09 17:29

from django.db import migrations


def migrate_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if not Owner.objects.filter(owners_phonenumber=flat.owners_phonenumber).exists():
            Owner.objects.create(name=flat.owner, owners_phonenumber=flat.owners_phonenumber, owner_phone_pure=flat.owner_phone_pure)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200309_1828'),
    ]

    operations = [
        migrations.RunPython(migrate_owner),
    ]
