# Generated by Django 2.2.4 on 2020-03-12 04:27

from django.db import migrations

def bind_owner_with_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    flats = Flat.objects.all()
    for owner in  Owner.objects.all():
        owner_flats = flats.filter(owners_phonenumber=owner.owner_phonenumber)
        owner.flats.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20200312_0727'),
    ]

    operations = [
        migrations.RunPython(bind_owner_with_flats),
    ]

