# Generated by Django 2.2.4 on 2020-03-14 18:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200314_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
