# Generated by Django 2.2.4 on 2020-03-14 18:05


from django.db import migrations


def make_empty_string(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        if owner.owner_phonenumber is None:
            owner.owner_phonenumber = ''
        if owner.owner_phone_pure is None:
            owner.owner_phone_pure = ''
        owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20200314_2104'),
    ]

    operations = [
        migrations.RunPython(make_empty_string),
    ]
